title: Site

fields:
  title:
    label: Title
    type:  text

  author: (meta)
    label: Author
    type:  text

  description:
    label: Description (meta)
    type:  markdown

  copyright:
    label: Copyright
    type:  markdown
